{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-secret
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- toYaml .Values.secrets.data | nindent 2 }}
{{- end }}
