{{- if .Values.ecrCredentialHelper.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.ecrCredentialHelper.serviceAccount.name }}
  namespace: kube-system
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    {{- with .Values.ecrCredentialHelper.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
